services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: root

    ports:
      - "3308:3306"
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    container_name: go-forum
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      DB_USER: user
      DB_PASS: root
      DB_NAME: forum
      DB_HOST: mysql

volumes:
  mysql_data:
